version: "3"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:2023.8.1
    container_name: homeassistant
    privileged: true
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000      
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123 #optional
    # devices:
      # - /path/to/device:/path/to/device #optional
    restart: unless-stopped
